name: s5_server
description: Decentralized content-addressed storage network
publish_to: none
version: 0.13.3

environment:
  sdk: ^3.0.0

dependencies:
  lib5: ^0.1.0
  alfred:
    git: https://github.com/redsolver/alfred.git
  belatuk_range_header: ^6.0.0
  base_codecs: ^1.0.1
  convert: ^3.0.2
  http: ^1.0.0
  minio:
    git: https://github.com/redsolver/minio-dart.git
  path: ^1.8.2
  hive: ^2.2.3
  toml: ^0.14.0
  cryptography: ^2.0.5
  mime: ^1.0.2
  tint: ^2.0.0
  filesize:
    git: https://github.com/redsolver/filesize.git
  string_scanner: ^1.1.1
  pool: ^1.5.1
  sqflite_common_ffi: ^2.2.0+1
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.73.0
  cancellation_token: ^2.0.0
  # ! disabled because the arweave-dart library is licensed GPL-2.0 and this repo is MIT
  # arweave:
  #   git: https://github.com/ardriveapp/arweave-dart.git

dependency_overrides:
  http: 1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  ffigen: ^8.0.2
